name: Re-Verb CI

on:
  pull_request:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npm run format:check

      - name: Build project
        run: npm run build
