name: Re-Verb CI

on:
  pull_request:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    env:
      SANITY_PROJECT_ID: ${{ vars.SANITY_PROJECT_ID }}
      SANITY_DATASET: ${{ vars.SANITY_DATASET }}
      SANITY_API_VERSION: ${{ vars.SANITY_API_VERSION }}
      SANITY_USE_CDN: ${{ vars.SANITY_USE_CDN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npm run format:check

      - name: Build project
        run: npm run build
